name: Pilot Program
favicon: null
layout_spectrum: 0.57702
typography_spectrum: 0.5373472785577178
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#625243'
    - '#bcae94'
    - '#6798da'
    - '#f8ebe0'
    - '#2f2311'
  brandStrength: 0.5625
  lightness: 0.9491933733224869
  saturation: 0.5236643252428621
  rhythmicContrast: 0.5
purpose: []
