name: Pilot Program
favicon: null
layout_spectrum: 0.18111
typography_spectrum: 0.5373472785577178
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.025449635228142142
  lightness: 0.9491933733224869
  saturation: 0.5236643252428621
  rhythmicContrast: 0.9416271294467151
purpose: []
